# Generated by Django 4.2.4 on 2023-08-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table_alter_orderitem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_ammount',
            new_name='paid_amount',
        ),
    ]
